@startuml
class Shoe {
    -ArrayList<Card> shoe
    +Shoe()
    +getNextCard()
    +printShoe()
    +setShoe()
}

class Card {
    +Card(int, int)
    +Print()
    +getImagePath()
    -int suit
    -int val
}

class Simulation {
    +Deal()
    +reset()

}

class EventHandler {
    +HandleBet()
}

class MyPanel {
    +MyPanel(Simulation s)
    -Simulation sim
}

class Runner {
	+main()
}

class GameController {
    +GameController(Simulation s, MyPanel p)
    -Simulation sim
    -MyPanel p
}

class Hand {

}

Shoe o-- Card
Hand o-- Card
Simulation --> Shoe : controls
Simulation --> Hand : controls
Runner --> MyPanel
Runner --> Simulation
Runner --> GameController
GameController --> MyPanel : Manages
GameController --> Simulation : Manages
@enduml